--// This file was created by XHider https://discord.com/invite/E2N7w35zkt 83491390959705

local l = {};
function l.TweenInstance(d, l, k, I, z)
	local B = (game:GetService("TweenService")):Create(l, TweenInfo.new(k, Enum.EasingStyle.Quad), { [I] = z });
	B:Play();
	return B;
end;
function l.UpdateContent(z, l, k, I)
	if l.Text ~= "" then
		k.Position = UDim2.new(0, 10, 0, 7);
		k.Size = UDim2.new(1, -60, 0, 16);
		local z = math.max(l.TextBounds.Y + 15, 45);
		I.Size = UDim2.new(1, 0, 0, z);
	end;
end;
function l.UpdateScrolling(I, l, k)
	(k:GetPropertyChangedSignal("AbsoluteContentSize")):Connect(function()
		l.CanvasSize = UDim2.new(0, 0, 0, k.AbsoluteContentSize.Y + 15);
	end);
end;
function l.MouseEvent(k, l, ...)
	local I = { ... };
	l.MouseEnter:Connect(I[1]);
	l.MouseLeave:Connect(I[2]);
end;
function l.MakeConfig(I, l, k)
	for l, I in next, l do
		if not k[l] then
			k[l] = I;
		end;
	end;
	return k;
end;
function l.MakeDraggable(I, l, k)
	local z = nil;
	local d = nil;
	local B = nil;
	local f = nil;
	local function w(l)
		local I = l.Position - B;
		local z = UDim2.new(f.X.Scale, f.X.Offset + I.X, f.Y.Scale, f.Y.Offset + I.Y);
		local d = (game:GetService("TweenService")):Create(k, TweenInfo.new(.2), { Position = z });
		d:Play();
	end;
	l.InputBegan:Connect(function(l)
		if l.UserInputType == Enum.UserInputType.MouseButton1 or l.UserInputType == Enum.UserInputType.Touch then
			z = true;
			B = l.Position;
			f = k.Position;
			l.Changed:Connect(function()
				if l.UserInputState == Enum.UserInputState.End then
					z = false;
				end;
			end);
		end;
	end);
	l.InputChanged:Connect(function(l)
		if l.UserInputType == Enum.UserInputType.MouseMovement or l.UserInputType == Enum.UserInputType.Touch then
			d = l;
		end;
	end);
	(game:GetService("UserInputService")).InputChanged:Connect(function(l)
		if l == d and z then
			w(l);
		end;
	end);
end;
function l.NewWindow(I, k)
	local z = I:MakeConfig({ Title = "AOV HUB", Description = "By Nguyen Anh Tuan" }, k or {});
	local d = Instance.new("ScreenGui");
	local B = Instance.new("Frame");
	local f = Instance.new("ImageLabel");
	local w = Instance.new("Frame");
	local q = Instance.new("UICorner");
	local J = Instance.new("Frame");
	local b = Instance.new("Frame");
	local K = Instance.new("Folder");
	local a = Instance.new("TextLabel");
	local V = Instance.new("ImageLabel");
	local E = Instance.new("TextLabel");
	local c = Instance.new("Folder");
	local i = Instance.new("Frame");
	local A = Instance.new("UIListLayout");
	local X = Instance.new("UIPadding");
	local C = Instance.new("TextButton");
	local Y = Instance.new("ImageLabel");
	local G = Instance.new("TextButton");
	local T = Instance.new("ImageLabel");
	local e = Instance.new("TextButton");
	local t = Instance.new("ImageLabel");
	local v = Instance.new("UIStroke");
	local s = Instance.new("Frame");
	local Q = Instance.new("Frame");
	local m = Instance.new("Frame");
	local y = Instance.new("UICorner");
	local u = Instance.new("ImageLabel");
	local H = Instance.new("TextBox");
	local h = Instance.new("ScrollingFrame");
	local g = Instance.new("UIPadding");
	local W = Instance.new("UIListLayout");
	local x = Instance.new("Frame");
	local S = Instance.new("Frame");
	local n = Instance.new("Folder");
	local R = Instance.new("UIPageLayout");
	local o = Instance.new("Frame");
	local p = Instance.new("TextLabel");
	local O = Instance.new("Frame");
	d.Name = "TeddyUI_Premium";
	d.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui");
	d.ZIndexBehavior = Enum.ZIndexBehavior.Sibling;
	B.Name = "DropShadowHolder";
	B.Parent = d;
	B.AnchorPoint = Vector2.new(.5, .5);
	B.BackgroundTransparency = 1.0;
	B.BorderSizePixel = 0;
	B.Position = UDim2.new(.5, 0, .5, 0);
	B.Size = UDim2.new(0, 555, 0, 350);
	B.ZIndex = 0;
	f.Name = "DropShadow";
	f.Parent = B;
	f.AnchorPoint = Vector2.new(.5, .5);
	f.BackgroundTransparency = 1.0;
	f.BorderSizePixel = 0;
	f.Position = UDim2.new(.5, 0, .5, 0);
	f.Size = UDim2.new(1, 47, 1, 47);
	f.ZIndex = 0;
	f.Image = "rbxassetid://6015897843";
	f.ImageColor3 = Color3.fromRGB(0, 0, 0);
	f.ImageTransparency = .5;
	f.ScaleType = Enum.ScaleType.Slice;
	f.SliceCenter = Rect.new(49, 49, 450, 450);
	w.Name = "Main";
	w.Parent = B;
	w.AnchorPoint = Vector2.new(.5, .5);
	w.BackgroundColor3 = Color3.fromRGB(9, 9, 9);
	w.BackgroundTransparency = .07;
	w.BorderColor3 = Color3.fromRGB(0, 0, 0);
	w.BorderSizePixel = 0;
	w.Position = UDim2.new(.5, 0, .5, 0);
	w.Size = UDim2.new(0, 555, 0, 350);
	q.Parent = w;
	J.Name = "Top";
	J.Parent = w;
	J.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	J.BackgroundTransparency = 1.0;
	J.BorderColor3 = Color3.fromRGB(0, 0, 0);
	J.BorderSizePixel = 0;
	J.Size = UDim2.new(1, 0, 0, 50);
	b.Name = "Line";
	b.Parent = J;
	b.BackgroundColor3 = Color3.fromRGB(179, 0, 255);
	b.BackgroundTransparency = .5;
	b.BorderColor3 = Color3.fromRGB(0, 0, 0);
	b.BorderSizePixel = 0;
	b.Position = UDim2.new(0, 0, 1, -1);
	b.Size = UDim2.new(1, 0, 0, 1);
	K.Name = "Left";
	K.Parent = J;
	a.Name = "NameHub";
	a.Parent = K;
	a.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	a.BackgroundTransparency = 1.0;
	a.BorderColor3 = Color3.fromRGB(0, 0, 0);
	a.BorderSizePixel = 0;
	a.Position = UDim2.new(0, 60, 0, 10);
	a.Size = UDim2.new(0, 470, 0, 20);
	a.Font = Enum.Font.GothamBold;
	a.Text = z.Title;
	a.TextColor3 = Color3.fromRGB(255, 255, 255);
	a.TextSize = 14.0;
	a.TextXAlignment = Enum.TextXAlignment.Left;
	V.Name = "LogoHub";
	V.Parent = K;
	V.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	V.BackgroundTransparency = 1.0;
	V.BorderColor3 = Color3.fromRGB(0, 0, 0);
	V.BorderSizePixel = 0;
	V.Position = UDim2.new(0, 10, 0, 5);
	V.Size = UDim2.new(0, 40, 0, 35);
	V.Image = "rbxassetid://83491390959705";
	E.Name = "Desc";
	E.Parent = K;
	E.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	E.BackgroundTransparency = 1.0;
	E.BorderColor3 = Color3.fromRGB(0, 0, 0);
	E.BorderSizePixel = 0;
	E.Position = UDim2.new(0, 60, 0, 27);
	E.Size = UDim2.new(0, 470, 1, -30);
	E.Font = Enum.Font.GothamBold;
	E.Text = z.Description;
	E.TextColor3 = Color3.fromRGB(100, 100, 100);
	E.TextSize = 12.0;
	E.TextXAlignment = Enum.TextXAlignment.Left;
	E.TextYAlignment = Enum.TextYAlignment.Top;
	c.Name = "Right";
	c.Parent = J;
	i.Parent = c;
	i.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	i.BackgroundTransparency = 1.0;
	i.BorderColor3 = Color3.fromRGB(0, 0, 0);
	i.BorderSizePixel = 0;
	i.Position = UDim2.new(1, -110, 0, 0);
	i.Size = UDim2.new(0, 110, 1, 0);
	A.Parent = i;
	A.FillDirection = Enum.FillDirection.Horizontal;
	A.SortOrder = Enum.SortOrder.LayoutOrder;
	A.Padding = UDim.new(0, 6);
	X.Parent = i;
	X.PaddingTop = UDim.new(0, 10);
	C.Name = "Minize";
	C.Parent = i;
	C.Active = false;
	C.AnchorPoint = Vector2.new(0, .5);
	C.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	C.BackgroundTransparency = 1.0;
	C.BorderColor3 = Color3.fromRGB(0, 0, 0);
	C.BorderSizePixel = 0;
	C.Selectable = false;
	C.Size = UDim2.new(0, 30, 0, 30);
	C.Text = "";
	Y.Name = "Icon";
	Y.Parent = C;
	Y.AnchorPoint = Vector2.new(.5, .5);
	Y.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	Y.BackgroundTransparency = 1.0;
	Y.BorderColor3 = Color3.fromRGB(0, 0, 0);
	Y.BorderSizePixel = 0;
	Y.Position = UDim2.new(.5, 0, .5, 0);
	Y.Size = UDim2.new(0, 20, 0, 20);
	Y.Image = "rbxassetid://136452605242985";
	Y.ImageRectOffset = Vector2.new(288, 672);
	Y.ImageRectSize = Vector2.new(96, 96);
	G.Name = "Large";
	G.Parent = i;
	G.Active = false;
	G.AnchorPoint = Vector2.new(0, .5);
	G.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	G.BackgroundTransparency = 1.0;
	G.BorderColor3 = Color3.fromRGB(0, 0, 0);
	G.BorderSizePixel = 0;
	G.Selectable = false;
	G.Size = UDim2.new(0, 30, 0, 30);
	G.Text = "";
	T.Name = "Icon";
	T.Parent = G;
	T.AnchorPoint = Vector2.new(.5, .5);
	T.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	T.BackgroundTransparency = 1.0;
	T.BorderColor3 = Color3.fromRGB(0, 0, 0);
	T.BorderSizePixel = 0;
	T.Position = UDim2.new(.5, 0, .5, 0);
	T.Size = UDim2.new(0, 18, 0, 18);
	T.Image = "rbxassetid://136452605242985";
	T.ImageRectOffset = Vector2.new(580, 194);
	T.ImageRectSize = Vector2.new(96, 96);
	e.Name = "Close";
	e.Parent = i;
	e.Active = false;
	e.AnchorPoint = Vector2.new(0, .5);
	e.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	e.BackgroundTransparency = 1.0;
	e.BorderColor3 = Color3.fromRGB(0, 0, 0);
	e.BorderSizePixel = 0;
	e.Selectable = false;
	e.Size = UDim2.new(0, 30, 0, 30);
	e.Text = "";
	e.MouseButton1Down:Connect(function()
		O.Visible = true;
		local l = Instance.new("Frame", O);
		l.BorderSizePixel = 0;
		l.BackgroundColor3 = Color3.fromRGB(19, 19, 19);
		l.AnchorPoint = Vector2.new(.5, .5);
		l.Size = UDim2.new(0, 400, 0, 150);
		l.Position = UDim2.new(.5, 0, .5, 0);
		l.BorderColor3 = Color3.fromRGB(0, 0, 0);
		l.Name = "Tat";
		local k = Instance.new("UIStroke", l);
		k.Transparency = .5;
		k.Color = Color3.fromRGB(101, 101, 101);
		local I = Instance.new("UICorner", l);
		I.CornerRadius = UDim.new(0, 5);
		local z = Instance.new("TextLabel", l);
		z.BorderSizePixel = 0;
		z.TextSize = 20;
		z.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
		z.FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal);
		z.TextColor3 = Color3.fromRGB(255, 255, 255);
		z.BackgroundTransparency = 1;
		z.Size = UDim2.new(0, 400, 0, 50);
		z.BorderColor3 = Color3.fromRGB(0, 0, 0);
		z.Text = "Are you sure";
		local B = Instance.new("TextButton", l);
		B.BorderSizePixel = 0;
		B.TextSize = 25;
		B.TextColor3 = Color3.fromRGB(255, 255, 255);
		B.BackgroundColor3 = Color3.fromRGB(5, 5, 5);
		B.FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal);
		B.AnchorPoint = Vector2.new(0, 1);
		B.Size = UDim2.new(0, 150, 0, 50);
		B.BorderColor3 = Color3.fromRGB(0, 0, 0);
		B.Text = "Yes";
		B.Position = UDim2.new(0, 40, 1, -40);
		B.MouseButton1Down:Connect(function()
			d:Destroy();
		end);
		local f = Instance.new("UICorner", B);
		local w = Instance.new("UIStroke", B);
		w.ApplyStrokeMode = Enum.ApplyStrokeMode.Border;
		w.Color = Color3.fromRGB(39, 39, 39);
		local q = Instance.new("TextButton", l);
		q.BorderSizePixel = 0;
		q.TextSize = 25;
		q.TextColor3 = Color3.fromRGB(255, 255, 255);
		q.BackgroundColor3 = Color3.fromRGB(5, 5, 5);
		q.FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal);
		q.AnchorPoint = Vector2.new(1, 1);
		q.Size = UDim2.new(0, 150, 0, 50);
		q.BorderColor3 = Color3.fromRGB(0, 0, 0);
		q.Text = "No";
		q.Position = UDim2.new(1, -40, 1, -40);
		q.MouseButton1Down:Connect(function()
			l:Destroy();
			O.Visible = false;
		end);
		local J = Instance.new("UICorner", q);
		local b = Instance.new("UIStroke", q);
		b.ApplyStrokeMode = Enum.ApplyStrokeMode.Border;
		b.Color = Color3.fromRGB(39, 39, 39);
	end);
	t.Name = "Icon";
	t.Parent = e;
	t.AnchorPoint = Vector2.new(.5, .5);
	t.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	t.BackgroundTransparency = 1.0;
	t.BorderColor3 = Color3.fromRGB(0, 0, 0);
	t.BorderSizePixel = 0;
	t.Position = UDim2.new(.5, 0, .5, 0);
	t.Size = UDim2.new(0, 20, 0, 20);
	t.Image = "rbxassetid://105957381820378";
	t.ImageRectOffset = Vector2.new(480, 0);
	t.ImageRectSize = Vector2.new(96, 96);
	v.Color = Color3.fromRGB(179, 0, 255);
	v.Transparency = .5;
	v.Parent = w;
	s.Name = "TabFrame";
	s.Parent = w;
	s.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	s.BackgroundTransparency = 1.0;
	s.BorderColor3 = Color3.fromRGB(0, 0, 0);
	s.BorderSizePixel = 0;
	s.Position = UDim2.new(0, 0, 0, 50);
	s.Size = UDim2.new(0, 144, 1, -50);
	Q.Name = "Line";
	Q.Parent = s;
	Q.BackgroundColor3 = Color3.fromRGB(179, 0, 255);
	Q.BackgroundTransparency = .5;
	Q.BorderColor3 = Color3.fromRGB(0, 0, 0);
	Q.BorderSizePixel = 0;
	Q.Position = UDim2.new(1, -1, 0, 0);
	Q.Size = UDim2.new(0, 1, 1, 0);
	m.Name = "SearchFrame";
	m.Parent = s;
	m.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	m.BackgroundTransparency = .95;
	m.BorderColor3 = Color3.fromRGB(0, 0, 0);
	m.BorderSizePixel = 0;
	m.Position = UDim2.new(0, 7, 0, 10);
	m.Size = UDim2.new(1, -14, 0, 30);
	y.CornerRadius = UDim.new(0, 3);
	y.Parent = m;
	u.Name = "IconSearch";
	u.Parent = m;
	u.AnchorPoint = Vector2.new(0, .5);
	u.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	u.BackgroundTransparency = 1.0;
	u.BorderColor3 = Color3.fromRGB(0, 0, 0);
	u.BorderSizePixel = 0;
	u.Position = UDim2.new(0, 10, .5, 0);
	u.Size = UDim2.new(0, 15, 0, 15);
	u.Image = "rbxassetid://71309835376233";
	H.Name = "SearchBox";
	H.Parent = m;
	H.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	H.BackgroundTransparency = 1.0;
	H.BorderColor3 = Color3.fromRGB(0, 0, 0);
	H.BorderSizePixel = 0;
	H.ClipsDescendants = true;
	H.Position = UDim2.new(0, 35, 0, 0);
	H.Size = UDim2.new(1, -35, 1, 0);
	H.Font = Enum.Font.GothamBold;
	H.PlaceholderText = "Search section or function";
	H.Text = "";
	H.TextColor3 = Color3.fromRGB(255, 255, 255);
	H.TextSize = 13.0;
	H.TextXAlignment = Enum.TextXAlignment.Left;
	h.Name = "ScrollingTab";
	h.Parent = s;
	h.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	h.BackgroundTransparency = 1.0;
	h.BorderColor3 = Color3.fromRGB(0, 0, 0);
	h.BorderSizePixel = 0;
	h.Position = UDim2.new(0, 0, 0, 50);
	h.Selectable = false;
	h.Size = UDim2.new(1, 0, 1, -50);
	h.ScrollBarThickness = 0;
	I:UpdateScrolling(h, W);
	g.Parent = h;
	g.PaddingBottom = UDim.new(0, 3);
	g.PaddingLeft = UDim.new(0, 7);
	g.PaddingRight = UDim.new(0, 7);
	g.PaddingTop = UDim.new(0, 3);
	W.Parent = h;
	W.SortOrder = Enum.SortOrder.LayoutOrder;
	x.Name = "LayoutFrame";
	x.Parent = w;
	x.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	x.BackgroundTransparency = 1.0;
	x.BorderColor3 = Color3.fromRGB(0, 0, 0);
	x.BorderSizePixel = 0;
	x.Position = UDim2.new(0, 144, 0, 50);
	x.Size = UDim2.new(1, -144, 1, -50);
	x.ClipsDescendants = true;
	S.Name = "RealLayout";
	S.Parent = x;
	S.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	S.BackgroundTransparency = 1.0;
	S.BorderColor3 = Color3.fromRGB(0, 0, 0);
	S.BorderSizePixel = 0;
	S.Position = UDim2.new(0, 0, 0, 40);
	S.Size = UDim2.new(1, 0, 1, -40);
	n.Name = "Layout List";
	n.Parent = S;
	R.Parent = n;
	R.SortOrder = Enum.SortOrder.LayoutOrder;
	R.EasingStyle = Enum.EasingStyle.Quad;
	R.TweenTime = .3;
	o.Name = "LayoutName";
	o.Parent = x;
	o.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	o.BackgroundTransparency = 1.0;
	o.BorderColor3 = Color3.fromRGB(0, 0, 0);
	o.BorderSizePixel = 0;
	o.Size = UDim2.new(1, 0, 0, 40);
	p.Parent = o;
	p.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	p.BackgroundTransparency = 1.0;
	p.BorderColor3 = Color3.fromRGB(0, 0, 0);
	p.BorderSizePixel = 0;
	p.Position = UDim2.new(0, 10, 0, 0);
	p.Size = UDim2.new(1, -10, 1, 0);
	p.Font = Enum.Font.GothamBold;
	p.Text = "";
	p.TextColor3 = Color3.fromRGB(255, 255, 255);
	p.TextSize = 13.0;
	p.TextXAlignment = Enum.TextXAlignment.Left;
	O.Name = "DropdownZone";
	O.Parent = w;
	O.BackgroundColor3 = Color3.fromRGB(0, 0, 0);
	O.BackgroundTransparency = 1;
	O.BorderColor3 = Color3.fromRGB(0, 0, 0);
	O.BorderSizePixel = 0;
	O.Size = UDim2.new(1, 0, 1, 0);
	O.Visible = false;
	I:MakeDraggable(J, B);
	local r = 0;
	local L = {};
	function L.T(I, k)
		local z = Instance.new("Frame");
		local d = Instance.new("Frame");
		local B = Instance.new("UICorner");
		local f = Instance.new("TextLabel");
		local w = Instance.new("TextButton");
		local q = Instance.new("ScrollingFrame");
		local J = Instance.new("UIPadding");
		local b = Instance.new("UIListLayout");
		z.Name = "TabDisable";
		z.Parent = h;
		z.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
		z.BackgroundTransparency = 1.0;
		z.BorderColor3 = Color3.fromRGB(0, 0, 0);
		z.BorderSizePixel = 0;
		z.Size = UDim2.new(1, 0, 0, 25);
		d.Name = "Choose";
		d.Parent = z;
		d.BackgroundColor3 = Color3.fromRGB(179, 0, 255);
		d.BorderColor3 = Color3.fromRGB(0, 0, 0);
		d.BorderSizePixel = 0;
		d.Position = UDim2.new(0, 0, 0, 5);
		d.Size = UDim2.new(0, 4, 0, 15);
		d.Visible = false;
		B.CornerRadius = UDim.new(1, 0);
		B.Parent = d;
		f.Name = "NameTab";
		f.Parent = z;
		f.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
		f.BackgroundTransparency = 1.0;
		f.BorderColor3 = Color3.fromRGB(0, 0, 0);
		f.BorderSizePixel = 0;
		f.Position = UDim2.new(0, 15, 0, 0);
		f.Size = UDim2.new(1, -15, 1, 0);
		f.Font = Enum.Font.GothamBold;
		f.Text = k;
		f.TextColor3 = Color3.fromRGB(255, 255, 255);
		f.TextSize = 12.0;
		f.TextTransparency = .3;
		f.TextXAlignment = Enum.TextXAlignment.Left;
		w.Name = "Click_Tab";
		w.Parent = z;
		w.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
		w.BackgroundTransparency = 1.0;
		w.BorderColor3 = Color3.fromRGB(0, 0, 0);
		w.BorderSizePixel = 0;
		w.Size = UDim2.new(1, 0, 1, 0);
		w.Font = Enum.Font.SourceSans;
		w.Text = "";
		w.TextColor3 = Color3.fromRGB(0, 0, 0);
		w.TextSize = 14.0;
		q.Name = "Layout";
		q.Parent = n;
		q.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
		q.BackgroundTransparency = 1.0;
		q.BorderColor3 = Color3.fromRGB(0, 0, 0);
		q.BorderSizePixel = 0;
		q.Selectable = false;
		q.Size = UDim2.new(1, 0, 1, 0);
		q.CanvasSize = UDim2.new(0, 0, 1, 0);
		q.ScrollBarThickness = 0;
		q.LayoutOrder = r;
		l:UpdateScrolling(q, b);
		J.Parent = q;
		J.PaddingBottom = UDim.new(0, 7);
		J.PaddingLeft = UDim.new(0, 10);
		J.PaddingRight = UDim.new(0, 7);
		b.Parent = q;
		b.SortOrder = Enum.SortOrder.LayoutOrder;
		b.Padding = UDim.new(0, 10);
		if r == 0 then
			f.TextTransparency = 0;
			d.Visible = true;
			R:JumpToIndex(0);
			p.Text = k;
		end;
		w.Activated:Connect(function()
			p.Text = k;
			for k, I in next, h:GetChildren() do
				if I:IsA("Frame") then
					l:TweenInstance(I.NameTab, .3, "TextTransparency", .3);
					I.Choose.Visible = false;
				end;
			end;
			l:TweenInstance(f, .2, "TextTransparency", 0);
			R:JumpToIndex(q.LayoutOrder);
			d.Visible = true;
		end);
		r = r + 1;
		local K = {};
		function K.AddSection(I, k)
			local z = Instance.new("Frame");
			local d = Instance.new("UICorner");
			local B = Instance.new("UIStroke");
			local f = Instance.new("Frame");
			local w = Instance.new("TextLabel");
			local J = Instance.new("Frame");
			local b = Instance.new("UIGradient");
			local K = Instance.new("Frame");
			local a = Instance.new("UIPadding");
			local V = Instance.new("UIListLayout");
			z.Name = "Section";
			z.Parent = q;
			z.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
			z.BackgroundTransparency = .98;
			z.BorderColor3 = Color3.fromRGB(0, 0, 0);
			z.BorderSizePixel = 0;
			z.Position = UDim2.new(1.36775815, 0, .545454562, 0);
			z.Size = UDim2.new(1, 0, 0, 55);
			d.CornerRadius = UDim.new(0, 4);
			d.Parent = z;
			B.Color = Color3.fromRGB(100, 100, 100);
			B.Thickness = 2;
			B.Transparency = .9200000166893;
			B.Parent = z;
			f.Name = "NameSection";
			f.Parent = z;
			f.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
			f.BackgroundTransparency = 1.0;
			f.BorderColor3 = Color3.fromRGB(0, 0, 0);
			f.BorderSizePixel = 0;
			f.Size = UDim2.new(1, 0, 0, 30);
			w.Name = "Title";
			w.Parent = f;
			w.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
			w.BackgroundTransparency = 1.0;
			w.BorderColor3 = Color3.fromRGB(0, 0, 0);
			w.BorderSizePixel = 0;
			w.Size = UDim2.new(1, 0, 1, 0);
			w.Font = Enum.Font.GothamBold;
			w.Text = k;
			w.TextColor3 = Color3.fromRGB(255, 255, 255);
			w.TextSize = 14.0;
			J.Name = "Line";
			J.Parent = f;
			J.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
			J.BorderColor3 = Color3.fromRGB(0, 0, 0);
			J.BorderSizePixel = 0;
			J.Position = UDim2.new(0, 0, 1, -2);
			J.Size = UDim2.new(1, 0, 0, 2);
			b.Color = ColorSequence.new({ ColorSequenceKeypoint.new(.0, Color3.fromRGB(24, 24, 25)), ColorSequenceKeypoint.new(.52, Color3.fromRGB(217, 0, 255)), ColorSequenceKeypoint.new(1.0, Color3.fromRGB(24, 24, 25)) });
			b.Transparency = NumberSequence.new({ NumberSequenceKeypoint.new(.0, .53), NumberSequenceKeypoint.new(.51, .0), NumberSequenceKeypoint.new(1.0, .51) });
			b.Parent = J;
			K.Name = "SectionList";
			K.Parent = z;
			K.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
			K.BackgroundTransparency = 1.0;
			K.BorderColor3 = Color3.fromRGB(0, 0, 0);
			K.BorderSizePixel = 0;
			K.Position = UDim2.new(0, 0, 0, 35);
			K.Size = UDim2.new(1, 0, 1, -35);
			a.Parent = K;
			a.PaddingBottom = UDim.new(0, 7);
			a.PaddingLeft = UDim.new(0, 7);
			a.PaddingRight = UDim.new(0, 7);
			a.PaddingTop = UDim.new(0, 7);
			V.Parent = K;
			V.SortOrder = Enum.SortOrder.LayoutOrder;
			V.Padding = UDim.new(0, 6);
			(V:GetPropertyChangedSignal("AbsoluteContentSize")):Connect(function()
				z.Size = UDim2.new(1, 0, 0, V.AbsoluteContentSize.Y + 55);
			end);
			local E = {};
			function E.AddToggle(I, k)
				local z = l:MakeConfig({
						Title = "Toggle < Missing Title >",
						Description = "",
						Default = false,
						Callback = function()
 
						end,
					}, k or {});
				local d = Instance.new("Frame");
				local B = Instance.new("UICorner");
				local f = Instance.new("TextLabel");
				local w = Instance.new("Frame");
				local q = Instance.new("UICorner");
				local J = Instance.new("Frame");
				local b = Instance.new("UICorner");
				local a = Instance.new("TextButton");
				local V = Instance.new("TextLabel");
				d.Name = "Toggle";
				d.Parent = K;
				d.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				d.BackgroundTransparency = .95;
				d.BorderColor3 = Color3.fromRGB(0, 0, 0);
				d.BorderSizePixel = 0;
				d.Size = UDim2.new(1, 0, 0, 35);
				B.CornerRadius = UDim.new(0, 3);
				B.Parent = d;
				f.Name = "Title";
				f.Parent = d;
				f.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				f.BackgroundTransparency = 1.0;
				f.BorderColor3 = Color3.fromRGB(0, 0, 0);
				f.BorderSizePixel = 0;
				f.Position = UDim2.new(0, 10, 0, 0);
				f.Size = UDim2.new(1, -60, 1, 0);
				f.Font = Enum.Font.GothamBold;
				f.Text = z.Title;
				f.TextColor3 = Color3.fromRGB(255, 255, 255);
				f.TextSize = 13.0;
				f.TextXAlignment = Enum.TextXAlignment.Left;
				w.Name = "ToggleCheck";
				w.Parent = d;
				w.AnchorPoint = Vector2.new(0, .5);
				w.BackgroundColor3 = Color3.fromRGB(60, 60, 60);
				w.BorderColor3 = Color3.fromRGB(0, 0, 0);
				w.BorderSizePixel = 0;
				w.Position = UDim2.new(1, -50, .5, 0);
				w.Size = UDim2.new(0, 40, 0, 22);
				q.CornerRadius = UDim.new(1, 0);
				q.Parent = w;
				J.Name = "Check";
				J.Parent = w;
				J.AnchorPoint = Vector2.new(0, .5);
				J.BackgroundColor3 = Color3.fromRGB(200, 200, 200);
				J.BorderColor3 = Color3.fromRGB(0, 0, 0);
				J.BorderSizePixel = 0;
				J.Position = UDim2.new(0, 3, .5, 0);
				J.Size = UDim2.new(0, 16, 0, 16);
				b.CornerRadius = UDim.new(1, 0);
				b.Parent = J;
				a.Name = "Toggle_Click";
				a.Parent = d;
				a.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				a.BackgroundTransparency = 1.0;
				a.BorderColor3 = Color3.fromRGB(0, 0, 0);
				a.BorderSizePixel = 0;
				a.Size = UDim2.new(1, 0, 1, 0);
				a.Font = Enum.Font.SourceSans;
				a.Text = "";
				a.TextColor3 = Color3.fromRGB(0, 0, 0);
				a.TextSize = 14.0;
				V.Name = "Content";
				V.Parent = d;
				V.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				V.BackgroundTransparency = 1.0;
				V.BorderColor3 = Color3.fromRGB(0, 0, 0);
				V.BorderSizePixel = 0;
				V.Position = UDim2.new(0, 10, 0, 22);
				V.Size = UDim2.new(1, -60, 1, 0);
				V.Font = Enum.Font.GothamBold;
				V.Text = z.Description;
				V.TextColor3 = Color3.fromRGB(100, 100, 100);
				V.TextSize = 12.0;
				V.TextXAlignment = Enum.TextXAlignment.Left;
				V.TextYAlignment = Enum.TextYAlignment.Top;
				l:UpdateContent(V, f, d);
				local E = { Value = z.Default };
				function E.Set(I, k)
					if k then
						l:TweenInstance(w, .3, "BackgroundColor3", Color3.fromRGB(170, 0, 255));
						l:TweenInstance(J, .3, "Position", UDim2.new(0, 22, .5, 0));
						l:TweenInstance(J, .3, "BackgroundColor3", Color3.fromRGB(255, 255, 255));
					else
						l:TweenInstance(w, .3, "BackgroundColor3", Color3.fromRGB(60, 60, 60));
						l:TweenInstance(J, .3, "BackgroundColor3", Color3.fromRGB(200, 200, 200));
						l:TweenInstance(J, .3, "Position", UDim2.new(0, 3, .5, 0));
					end;
					I.Value = k;
					z.Callback(k);
				end;
				E:Set(E.Value);
				a.Activated:Connect(function()
					E:Set(not E.Value);
				end);
			end;
			function E.AddButton(I, k)
				local z = l:MakeConfig({ Title = "Button < Missing Title >", Description = "", Callback = function()
 
						end }, k or {});
				local d = Instance.new("Frame");
				local B = Instance.new("UICorner");
				local f = Instance.new("TextLabel");
				local w = Instance.new("TextButton");
				local q = Instance.new("TextLabel");
				local J = Instance.new("ImageLabel");
				d.Name = "Button";
				d.Parent = K;
				d.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				d.BackgroundTransparency = .95;
				d.BorderColor3 = Color3.fromRGB(0, 0, 0);
				d.BorderSizePixel = 0;
				d.Size = UDim2.new(1, 0, 0, 35);
				B.CornerRadius = UDim.new(0, 3);
				B.Parent = d;
				f.Name = "Title";
				f.Parent = d;
				f.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				f.BackgroundTransparency = 1.0;
				f.BorderColor3 = Color3.fromRGB(0, 0, 0);
				f.BorderSizePixel = 0;
				f.Position = UDim2.new(0, 10, 0, 0);
				f.Size = UDim2.new(1, -60, 1, 0);
				f.Font = Enum.Font.GothamBold;
				f.Text = z.Title;
				f.TextColor3 = Color3.fromRGB(255, 255, 255);
				f.TextSize = 13.0;
				f.TextXAlignment = Enum.TextXAlignment.Left;
				w.Name = "Button_Click";
				w.Parent = d;
				w.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				w.BackgroundTransparency = 1.0;
				w.BorderColor3 = Color3.fromRGB(0, 0, 0);
				w.BorderSizePixel = 0;
				w.Size = UDim2.new(1, 0, 1, 0);
				w.Font = Enum.Font.SourceSans;
				w.Text = "";
				w.TextColor3 = Color3.fromRGB(0, 0, 0);
				w.TextSize = 14.0;
				q.Name = "Content";
				q.Parent = d;
				q.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				q.BackgroundTransparency = 1.0;
				q.BorderColor3 = Color3.fromRGB(0, 0, 0);
				q.BorderSizePixel = 0;
				q.Position = UDim2.new(0, 10, 0, 22);
				q.Size = UDim2.new(1, -60, 1, 0);
				q.Font = Enum.Font.GothamBold;
				q.Text = z.Description;
				q.TextColor3 = Color3.fromRGB(100, 100, 100);
				q.TextSize = 12.0;
				q.TextXAlignment = Enum.TextXAlignment.Left;
				q.TextYAlignment = Enum.TextYAlignment.Top;
				J.Parent = d;
				J.AnchorPoint = Vector2.new(0, .5);
				J.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				J.BackgroundTransparency = 1.0;
				J.BorderColor3 = Color3.fromRGB(0, 0, 0);
				J.BorderSizePixel = 0;
				J.Position = UDim2.new(1, -35, .5, 0);
				J.Size = UDim2.new(0, 24, 0, 24);
				J.Image = "rbxassetid://85905776508942";
				l:UpdateContent(q, f, d);
				w.Activated:Connect(function()
					d.BackgroundTransparency = .97;
					z.Callback();
					l:TweenInstance(d, .2, "BackgroundTransparency", .95);
				end);
			end;
			function E.AddDropdown(I, k)
				local z = l:MakeConfig({
						Title = "Dropdown",
						Description = "",
						Values = {},
						Default = "",
						Callback = function()
 
						end,
					}, k or {});
				local d = Instance.new("Frame");
				local B = Instance.new("UICorner");
				local f = Instance.new("TextLabel");
				local w = Instance.new("TextLabel");
				local q = Instance.new("Frame");
				local J = Instance.new("UICorner");
				local b = Instance.new("TextLabel");
				local a = Instance.new("UITextSizeConstraint");
				local V = Instance.new("TextButton");
				local E = Instance.new("ImageLabel");
				local c = Instance.new("Frame");
				local i = Instance.new("UIStroke");
				local A = Instance.new("UICorner");
				local X = Instance.new("Frame");
				local C = Instance.new("TextLabel");
				local Y = Instance.new("Frame");
				local G = Instance.new("UICorner");
				local T = Instance.new("UIStroke");
				local e = Instance.new("ImageLabel");
				local t = Instance.new("TextBox");
				local v = Instance.new("TextButton");
				local s = Instance.new("ImageLabel");
				local Q = Instance.new("ScrollingFrame");
				local m = Instance.new("UICorner");
				local y = Instance.new("UIListLayout");
				local u = Instance.new("UIPadding");
				d.Name = "Dropdown";
				d.Parent = K;
				d.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				d.BackgroundTransparency = .95;
				d.BorderColor3 = Color3.fromRGB(0, 0, 0);
				d.BorderSizePixel = 0;
				d.Size = UDim2.new(1, 0, 0, 35);
				B.CornerRadius = UDim.new(0, 3);
				B.Parent = d;
				f.Name = "Title";
				f.Parent = d;
				f.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				f.BackgroundTransparency = 1.0;
				f.BorderColor3 = Color3.fromRGB(0, 0, 0);
				f.BorderSizePixel = 0;
				f.Position = UDim2.new(0, 10, 0, 0);
				f.Size = UDim2.new(1, -60, 1, 0);
				f.Font = Enum.Font.GothamBold;
				f.Text = z.Title;
				f.TextColor3 = Color3.fromRGB(255, 255, 255);
				f.TextSize = 13.0;
				f.TextXAlignment = Enum.TextXAlignment.Left;
				w.Name = "Content";
				w.Parent = d;
				w.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				w.BackgroundTransparency = 1.0;
				w.BorderColor3 = Color3.fromRGB(0, 0, 0);
				w.BorderSizePixel = 0;
				w.Position = UDim2.new(0, 10, 0, 22);
				w.Size = UDim2.new(1, -60, 1, 0);
				w.Font = Enum.Font.GothamBold;
				w.Text = z.Description;
				w.TextColor3 = Color3.fromRGB(100, 100, 100);
				w.TextSize = 12.0;
				w.TextXAlignment = Enum.TextXAlignment.Left;
				w.TextYAlignment = Enum.TextYAlignment.Top;
				q.Name = "Selects";
				q.Parent = d;
				q.AnchorPoint = Vector2.new(0, .5);
				q.BackgroundColor3 = Color3.fromRGB(20, 20, 20);
				q.BorderColor3 = Color3.fromRGB(0, 0, 0);
				q.BorderSizePixel = 0;
				q.Position = UDim2.new(1, -90, .5, 0);
				q.Size = UDim2.new(0, 80, 0, 25);
				J.CornerRadius = UDim.new(0, 5);
				J.Parent = q;
				b.Name = "SelectText";
				b.Parent = q;
				b.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				b.BackgroundTransparency = 1.0;
				b.BorderColor3 = Color3.fromRGB(0, 0, 0);
				b.BorderSizePixel = 0;
				b.Position = UDim2.new(0, 3, 0, 0);
				b.Size = UDim2.new(1, -25, 1, 0);
				b.Font = Enum.Font.GothamBold;
				b.Text = "";
				b.TextColor3 = Color3.fromRGB(255, 255, 255);
				b.TextScaled = true;
				b.TextSize = 1.0;
				b.TextWrapped = true;
				a.Parent = b;
				a.MaxTextSize = 12;
				V.Name = "Drop_Click";
				V.Parent = q;
				V.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				V.BackgroundTransparency = 1.0;
				V.BorderColor3 = Color3.fromRGB(0, 0, 0);
				V.BorderSizePixel = 0;
				V.Size = UDim2.new(1, 0, 1, 0);
				V.Font = Enum.Font.SourceSans;
				V.Text = "";
				V.TextColor3 = Color3.fromRGB(0, 0, 0);
				V.TextSize = 14.0;
				E.Parent = q;
				E.AnchorPoint = Vector2.new(0, .5);
				E.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				E.BackgroundTransparency = 1.0;
				E.BorderColor3 = Color3.fromRGB(0, 0, 0);
				E.BorderSizePixel = 0;
				E.Position = UDim2.new(1, -20, .5, 0);
				E.Size = UDim2.new(0, 15, 0, 15);
				E.Image = "rbxassetid://80845745785361";
				l:UpdateContent(w, f, d);
				c.Name = "DropdownList";
				c.Parent = O;
				c.AnchorPoint = Vector2.new(.5, .5);
				c.BackgroundColor3 = Color3.fromRGB(18, 18, 18);
				c.BorderColor3 = Color3.fromRGB(0, 0, 0);
				c.BorderSizePixel = 0;
				c.Position = UDim2.new(.5, 0, .5, 0);
				c.Size = UDim2.new(0, 400, 0, 250);
				c.Visible = false;
				i.Color = Color3.fromRGB(100, 100, 100);
				i.Transparency = .5;
				i.Parent = c;
				A.CornerRadius = UDim.new(0, 5);
				A.Parent = c;
				X.Name = "Topbar";
				X.Parent = c;
				X.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				X.BackgroundTransparency = 1.0;
				X.BorderColor3 = Color3.fromRGB(0, 0, 0);
				X.BorderSizePixel = 0;
				X.Size = UDim2.new(1, 0, 0, 50);
				C.Name = "Title";
				C.Parent = X;
				C.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				C.BackgroundTransparency = 1.0;
				C.BorderColor3 = Color3.fromRGB(0, 0, 0);
				C.BorderSizePixel = 0;
				C.Position = UDim2.new(0, 15, 0, 0);
				C.Size = UDim2.new(1, -200, 1, -5);
				C.Font = Enum.Font.GothamBold;
				C.Text = z.Title;
				C.TextColor3 = Color3.fromRGB(255, 255, 255);
				C.TextSize = 14.0;
				C.TextWrapped = true;
				C.TextXAlignment = Enum.TextXAlignment.Left;
				Y.Name = "SearchFrame";
				Y.Parent = X;
				Y.BackgroundColor3 = Color3.fromRGB(15, 15, 15);
				Y.BorderColor3 = Color3.fromRGB(0, 0, 0);
				Y.BorderSizePixel = 0;
				Y.Position = UDim2.new(1, -150, 0, 8);
				Y.Size = UDim2.new(0, 100, 0, 30);
				G.CornerRadius = UDim.new(0, 5);
				G.Parent = Y;
				T.Color = Color3.fromRGB(100, 100, 100);
				T.Transparency = .74000000953674;
				T.Parent = Y;
				e.Name = "IconSearch";
				e.Parent = Y;
				e.AnchorPoint = Vector2.new(0, .5);
				e.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				e.BackgroundTransparency = 1.0;
				e.BorderColor3 = Color3.fromRGB(0, 0, 0);
				e.BorderSizePixel = 0;
				e.Position = UDim2.new(0, 10, .5, 0);
				e.Size = UDim2.new(0, 15, 0, 15);
				e.Image = "rbxassetid://71309835376233";
				t.Parent = Y;
				t.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				t.BackgroundTransparency = 1.0;
				t.BorderColor3 = Color3.fromRGB(0, 0, 0);
				t.BorderSizePixel = 0;
				t.Position = UDim2.new(0, 35, 0, 0);
				t.Size = UDim2.new(1, -35, 1, 0);
				t.Font = Enum.Font.GothamBold;
				t.PlaceholderText = "Search...";
				t.Text = "";
				t.TextColor3 = Color3.fromRGB(255, 255, 255);
				t.TextSize = 12.0;
				t.TextXAlignment = Enum.TextXAlignment.Left;
				v.Name = "Click_Dropdown";
				v.Parent = X;
				v.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				v.BackgroundTransparency = 1.0;
				v.BorderColor3 = Color3.fromRGB(0, 0, 0);
				v.BorderSizePixel = 0;
				v.Position = UDim2.new(1, -40, 0, 8);
				v.Size = UDim2.new(0, 30, 0, 30);
				v.Text = "";
				s.Name = "Icon";
				s.Parent = v;
				s.AnchorPoint = Vector2.new(.5, .5);
				s.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				s.BackgroundTransparency = 1.0;
				s.BorderColor3 = Color3.fromRGB(0, 0, 0);
				s.BorderSizePixel = 0;
				s.Position = UDim2.new(.5, 0, .5, 0);
				s.Size = UDim2.new(0, 20, 0, 20);
				s.Image = "rbxassetid://105957381820378";
				s.ImageRectOffset = Vector2.new(480, 0);
				s.ImageRectSize = Vector2.new(96, 96);
				Q.Name = "Real_List";
				Q.Parent = c;
				Q.BackgroundColor3 = Color3.fromRGB(12, 12, 12);
				Q.BorderColor3 = Color3.fromRGB(0, 0, 0);
				Q.BorderSizePixel = 0;
				Q.Position = UDim2.new(0, 10, 0, 50);
				Q.Selectable = false;
				Q.ScrollBarThickness = 0;
				Q.Size = UDim2.new(1, -20, 1, -60);
				l:UpdateScrolling(Q, y);
				m.CornerRadius = UDim.new(0, 5);
				m.Parent = Q;
				y.Parent = Q;
				y.SortOrder = Enum.SortOrder.LayoutOrder;
				y.Padding = UDim.new(0, 5);
				u.Parent = Q;
				u.PaddingBottom = UDim.new(0, 7);
				u.PaddingLeft = UDim.new(0, 7);
				u.PaddingRight = UDim.new(0, 7);
				u.PaddingTop = UDim.new(0, 7);
				local H = Instance.new("UICorner");
				H.Parent = O;
				V.Activated:Connect(function()
					O.Visible = true;
					c.Visible = true;
					l:TweenInstance(O, .3, "BackgroundTransparency", .3);
				end);
				v.Activated:Connect(function()
					c.Visible = false;
					l:TweenInstance(O, .3, "BackgroundTransparency", 1);
					wait(.3);
					O.Visible = false;
				end);
				local h = { Value = z.Default };
				function h.Set(I, k)
					h.Value = k or h.Value;
					for k, I in next, Q:GetChildren() do
						if I:IsA("Frame") then
							if table.find(h.Value, I.Title.Text) then
								l:TweenInstance(I, .3, "BackgroundTransparency", 0);
								l:TweenInstance(I.Title, .3, "TextTransparency", 0);
							else
								l:TweenInstance(I, .3, "BackgroundTransparency", .98);
								l:TweenInstance(I.Title, .3, "TextTransparency", .5);
							end;
						end;
					end;
					local d = table.concat(h.Value, ",");
					if d == "" then
						b.Text = "";
					else
						b.Text = d;
					end;
					z.Callback(z.Multi and h.Value or table.concat(h.Value, ""));
				end;
				function h.Add(k, l)
					local I = Instance.new("Frame");
					local d = Instance.new("UICorner");
					local B = Instance.new("TextButton");
					local f = Instance.new("TextLabel");
					local w = Instance.new("UIGradient");
					I.Name = "Option 2";
					I.Parent = Q;
					I.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
					I.BackgroundTransparency = .98;
					I.BorderColor3 = Color3.fromRGB(0, 0, 0);
					I.BorderSizePixel = 0;
					I.Size = UDim2.new(1, 0, 0, 35);
					d.CornerRadius = UDim.new(0, 4);
					d.Parent = I;
					B.Name = "Option2_Click";
					B.Parent = I;
					B.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
					B.BackgroundTransparency = 1.0;
					B.BorderColor3 = Color3.fromRGB(0, 0, 0);
					B.BorderSizePixel = 0;
					B.Size = UDim2.new(1, 0, 1, 0);
					B.Font = Enum.Font.SourceSans;
					B.Text = "";
					B.TextColor3 = Color3.fromRGB(0, 0, 0);
					B.TextSize = 14.0;
					f.Name = "Title";
					f.Parent = I;
					f.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
					f.BackgroundTransparency = 1.0;
					f.BorderColor3 = Color3.fromRGB(0, 0, 0);
					f.BorderSizePixel = 0;
					f.Size = UDim2.new(1, 0, 1, 0);
					f.Font = Enum.Font.GothamBold;
					f.Text = l;
					f.TextColor3 = Color3.fromRGB(255, 255, 255);
					f.TextSize = 13.0;
					f.TextTransparency = .5;
					w.Color = ColorSequence.new({ ColorSequenceKeypoint.new(.0, Color3.fromRGB(0, 0, 0)), ColorSequenceKeypoint.new(.51, Color3.fromRGB(201, 5, 255)), ColorSequenceKeypoint.new(1.0, Color3.fromRGB(0, 0, 0)) });
					w.Rotation = .99000000953674;
					w.Transparency = NumberSequence.new({ NumberSequenceKeypoint.new(.0, .5), NumberSequenceKeypoint.new(.5, .49), NumberSequenceKeypoint.new(1.0, .44) });
					w.Parent = I;
					B.Activated:Connect(function()
						if z.Multi then
							if I.BackgroundTransparency < .95 then
								for l, k in next, h.Value do
									if k == f.Text then
										table.remove(h.Value, l);
									end;
								end;
								h:Set(h.Value);
							else
								table.insert(h.Value, f.Text);
								h:Set(h.Value);
							end;
						else
							h.Value = { f.Text };
							h:Set(h.Value);
						end;
					end);
				end;
				function h.Clear(l)
					for l, k in next, Q:GetChildren() do
						if k:IsA("Frame") then
							k:Destroy();
						end;
					end;
				end;
				function h.Refresh(k, l)
					k:Clear();
					for l, I in next, l do
						k:Add(I);
					end;
				end;
				h:Refresh(z.Values);
				h:Set(typeof(z.Default) == "string" and { z.Default } or z.Default);
				return h;
			end;
			function E.AddInput(I, k)
				local z = l:MakeConfig({
						Title = "Textbox",
						Description = "",
						PlaceHolder = "",
						Default = "",
						Callback = function()
 
						end,
					}, k or {});
				local d = Instance.new("Frame");
				local B = Instance.new("UICorner");
				local f = Instance.new("TextLabel");
				local w = Instance.new("TextLabel");
				local q = Instance.new("Frame");
				local J = Instance.new("UICorner");
				local b = Instance.new("TextBox");
				local a = Instance.new("ImageLabel");
				d.Name = "Input";
				d.Parent = K;
				d.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				d.BackgroundTransparency = .95;
				d.BorderColor3 = Color3.fromRGB(0, 0, 0);
				d.BorderSizePixel = 0;
				d.Size = UDim2.new(1, 0, 0, 35);
				B.CornerRadius = UDim.new(0, 3);
				B.Parent = d;
				f.Name = "Title";
				f.Parent = d;
				f.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				f.BackgroundTransparency = 1.0;
				f.BorderColor3 = Color3.fromRGB(0, 0, 0);
				f.BorderSizePixel = 0;
				f.Position = UDim2.new(0, 10, 0, 0);
				f.Size = UDim2.new(1, -60, 1, 0);
				f.Font = Enum.Font.GothamBold;
				f.Text = z.Title;
				f.TextColor3 = Color3.fromRGB(255, 255, 255);
				f.TextSize = 13.0;
				f.TextXAlignment = Enum.TextXAlignment.Left;
				w.Name = "Content";
				w.Parent = d;
				w.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				w.BackgroundTransparency = 1.0;
				w.BorderColor3 = Color3.fromRGB(0, 0, 0);
				w.BorderSizePixel = 0;
				w.Position = UDim2.new(0, 10, 0, 22);
				w.Size = UDim2.new(1, -160, 1, 0);
				w.Font = Enum.Font.GothamBold;
				w.Text = z.Description;
				w.TextColor3 = Color3.fromRGB(100, 100, 100);
				w.TextSize = 12.0;
				w.TextXAlignment = Enum.TextXAlignment.Left;
				w.TextYAlignment = Enum.TextYAlignment.Top;
				l:UpdateContent(w, f, d);
				q.Name = "TextboxFrame";
				q.Parent = d;
				q.AnchorPoint = Vector2.new(0, .5);
				q.BackgroundColor3 = Color3.fromRGB(25, 25, 25);
				q.BorderColor3 = Color3.fromRGB(0, 0, 0);
				q.BorderSizePixel = 0;
				q.Position = UDim2.new(1, -140, .5, 0);
				q.Size = UDim2.new(0, 130, 0, 28);
				J.CornerRadius = UDim.new(0, 3);
				J.Parent = q;
				b.Name = "RealTextBox";
				b.Parent = q;
				b.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				b.BackgroundTransparency = 1.0;
				b.BorderColor3 = Color3.fromRGB(0, 0, 0);
				b.BorderSizePixel = 0;
				b.Position = UDim2.new(0, 35, 0, 0);
				b.Size = UDim2.new(1, -35, 1, 0);
				b.Font = Enum.Font.GothamBold;
				b.PlaceholderText = z.PlaceHolder;
				b.Text = z.Default;
				b.TextColor3 = Color3.fromRGB(255, 255, 255);
				b.TextSize = 12.0;
				b.TextXAlignment = Enum.TextXAlignment.Left;
				a.Name = "WritingIcon";
				a.Parent = q;
				a.AnchorPoint = Vector2.new(0, .5);
				a.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				a.BackgroundTransparency = 1.0;
				a.BorderColor3 = Color3.fromRGB(0, 0, 0);
				a.BorderSizePixel = 0;
				a.Position = UDim2.new(0, 10, .5, 0);
				a.Size = UDim2.new(0, 15, 0, 15);
				a.Image = "rbxassetid://126409600467363";
				b.FocusLost:Connect(function()
					z.Callback(b.Text);
				end);
				z.Callback(b.Text);
			end;
			function E.AddSlider(I, k)
				local z = l:MakeConfig({
						Title = "Slider < Missing Title >",
						Description = "",
						Max = 100,
						Min = 1,
						Increment = 1,
						Default = 1,
						Callback = function()
 
						end,
					}, k or {});
				local d = Instance.new("Frame");
				local B = Instance.new("UICorner");
				local f = Instance.new("TextLabel");
				local w = Instance.new("TextLabel");
				local q = Instance.new("Frame");
				local J = Instance.new("UICorner");
				local b = Instance.new("Frame");
				local a = Instance.new("UICorner");
				local V = Instance.new("Frame");
				local E = Instance.new("UICorner");
				local c = Instance.new("TextBox");
				local i = Instance.new("UICorner");
				d.Name = "Slider";
				d.Parent = K;
				d.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				d.BackgroundTransparency = .95;
				d.BorderColor3 = Color3.fromRGB(0, 0, 0);
				d.BorderSizePixel = 0;
				d.Size = UDim2.new(1, 0, 0, 35);
				B.CornerRadius = UDim.new(0, 3);
				B.Parent = d;
				f.Name = "Title";
				f.Parent = d;
				f.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				f.BackgroundTransparency = 1.0;
				f.BorderColor3 = Color3.fromRGB(0, 0, 0);
				f.BorderSizePixel = 0;
				f.Position = UDim2.new(0, 10, 0, 0);
				f.Size = UDim2.new(1, -60, 1, 0);
				f.Font = Enum.Font.GothamBold;
				f.Text = z.Title;
				f.TextColor3 = Color3.fromRGB(255, 255, 255);
				f.TextSize = 13.0;
				f.TextXAlignment = Enum.TextXAlignment.Left;
				w.Name = "Content";
				w.Parent = d;
				w.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				w.BackgroundTransparency = 1.0;
				w.BorderColor3 = Color3.fromRGB(0, 0, 0);
				w.BorderSizePixel = 0;
				w.Position = UDim2.new(0, 10, 0, 22);
				w.Size = UDim2.new(1, -160, 1, 0);
				w.Font = Enum.Font.GothamBold;
				w.Text = z.Description;
				w.TextColor3 = Color3.fromRGB(100, 100, 100);
				w.TextSize = 12.0;
				w.TextXAlignment = Enum.TextXAlignment.Left;
				w.TextYAlignment = Enum.TextYAlignment.Top;
				l:UpdateContent(w, f, d);
				q.Name = "SliderFrame";
				q.Parent = d;
				q.AnchorPoint = Vector2.new(0, .5);
				q.BackgroundColor3 = Color3.fromRGB(20, 20, 20);
				q.BorderColor3 = Color3.fromRGB(0, 0, 0);
				q.BorderSizePixel = 0;
				q.Position = UDim2.new(1, -140, .5, 0);
				q.Size = UDim2.new(0, 130, 0, 8);
				J.CornerRadius = UDim.new(1, 0);
				J.Parent = q;
				b.Name = "SliderDraggable";
				b.Parent = q;
				b.BackgroundColor3 = Color3.fromRGB(179, 0, 255);
				b.BorderColor3 = Color3.fromRGB(0, 0, 0);
				b.BorderSizePixel = 0;
				b.Size = UDim2.new(0, 20, 1, 0);
				a.CornerRadius = UDim.new(1, 0);
				a.Parent = b;
				V.Name = "Circle";
				V.Parent = b;
				V.AnchorPoint = Vector2.new(0, .100000001);
				V.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				V.BorderColor3 = Color3.fromRGB(0, 0, 0);
				V.BorderSizePixel = 0;
				V.Position = UDim2.new(1, -6, 0, 0);
				V.Size = UDim2.new(0, 12, 0, 12);
				E.CornerRadius = UDim.new(1, 0);
				E.Parent = V;
				c.Name = "SliderValue";
				c.Parent = d;
				c.AnchorPoint = Vector2.new(0, .5);
				c.BackgroundColor3 = Color3.fromRGB(178, 0, 254);
				c.BorderColor3 = Color3.fromRGB(0, 0, 0);
				c.BorderSizePixel = 0;
				c.Position = UDim2.new(1, -185, .5, 0);
				c.Size = UDim2.new(0, 35, 0, 20);
				c.Font = Enum.Font.GothamBold;
				c.PlaceholderColor3 = Color3.fromRGB(178, 178, 178);
				c.PlaceholderText = "...";
				c.Text = "";
				c.TextColor3 = Color3.fromRGB(255, 255, 255);
				c.TextSize = 11.0;
				i.CornerRadius = UDim.new(0, 2);
				i.Parent = c;
				local A = { Value = z.Default };
				local X = false;
				local function C(l, k)
					local I = math.floor(l / k + math.sign(l) * .5) * k;
					if I < 0 then
						I = I + k;
					end;
					return I;
				end;
				function A.Set(k, l)
					l = math.clamp(C(l, z.Increment), z.Min, z.Max);
					A.Value = l;
					c.Text = tostring(l);
					((game:GetService("TweenService")):Create(b, TweenInfo.new(.3, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), { Size = UDim2.fromScale((l - z.Min) / (z.Max - z.Min), 1) })):Play();
				end;
				q.InputBegan:Connect(function(l)
					if l.UserInputType == Enum.UserInputType.MouseButton1 then
						X = true;
					end;
				end);
				q.InputEnded:Connect(function(l)
					if l.UserInputType == Enum.UserInputType.MouseButton1 then
						X = false;
						z.Callback(A.Value);
					end;
				end);
				(game:GetService("UserInputService")).InputChanged:Connect(function(l)
					if X and l.UserInputType == Enum.UserInputType.MouseMovement then
						local k = math.clamp((l.Position.X - q.AbsolutePosition.X) / q.AbsoluteSize.X, 0, 1);
						A:Set(z.Min + (z.Max - z.Min) * k);
					end;
				end);
				(c:GetPropertyChangedSignal("Text")):Connect(function()
					local l = c.Text:gsub("[^%d]", "");
					if l ~= "" then
						local k = math.min(tonumber(l), z.Max);
						c.Text = tostring(k);
					else
						c.Text = tostring(l);
					end;
				end);
				c.FocusLost:Connect(function()
					if c.Text ~= "" then
						A:Set(tonumber(c.Text));
					else
						A:Set(0);
					end;
				end);
				A:Set(tonumber(z.Default));
				return A;
			end;
			function E.AddSeperator(k, l)
				local I = Instance.new("Frame");
				local z = Instance.new("TextLabel");
				I.Name = "Seperator";
				I.Parent = K;
				I.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				I.BackgroundTransparency = 1.0;
				I.BorderColor3 = Color3.fromRGB(0, 0, 0);
				I.BorderSizePixel = 0;
				I.Size = UDim2.new(1, 0, 0, 20);
				z.Name = "Title";
				z.Parent = I;
				z.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				z.BackgroundTransparency = 1.0;
				z.BorderColor3 = Color3.fromRGB(0, 0, 0);
				z.BorderSizePixel = 0;
				z.Position = UDim2.new(0, 10, 0, 0);
				z.Size = UDim2.new(1, -10, 1, 0);
				z.Font = Enum.Font.GothamBold;
				z.Text = l;
				z.TextColor3 = Color3.fromRGB(255, 255, 255);
				z.TextSize = 13.0;
				z.TextXAlignment = Enum.TextXAlignment.Left;
			end;
			function E.AddParagraph(I, k)
				local z = l:MakeConfig({ Title = "Paragraph < Missing Title >", Content = "" }, k or {});
				local d = Instance.new("Frame");
				local B = Instance.new("UICorner");
				local f = Instance.new("TextLabel");
				local w = Instance.new("TextLabel");
				local q = {};
				d.Name = "Paragraph";
				d.Parent = K;
				d.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				d.BackgroundTransparency = .95;
				d.BorderColor3 = Color3.fromRGB(0, 0, 0);
				d.BorderSizePixel = 0;
				d.Size = UDim2.new(1, 0, 0, 45);
				B.CornerRadius = UDim.new(0, 3);
				B.Parent = d;
				f.Name = "Title";
				f.Parent = d;
				f.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				f.BackgroundTransparency = 1.0;
				f.BorderColor3 = Color3.fromRGB(0, 0, 0);
				f.BorderSizePixel = 0;
				f.Position = UDim2.new(0, 10, 0, 7);
				f.Size = UDim2.new(1, -60, 0, 16);
				f.Font = Enum.Font.GothamBold;
				f.Text = z.Title;
				f.TextColor3 = Color3.fromRGB(255, 255, 255);
				f.TextSize = 13.0;
				f.TextXAlignment = Enum.TextXAlignment.Left;
				w.Name = "Content";
				w.Parent = d;
				w.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
				w.BackgroundTransparency = 1.0;
				w.BorderColor3 = Color3.fromRGB(0, 0, 0);
				w.BorderSizePixel = 0;
				w.Position = UDim2.new(0, 10, 0, 22);
				w.Size = UDim2.new(1, -10, 1, 0);
				w.Font = Enum.Font.GothamBold;
				w.Text = z.Content;
				w.TextColor3 = Color3.fromRGB(100, 100, 100);
				w.TextSize = 12.0;
				w.TextXAlignment = Enum.TextXAlignment.Left;
				w.TextYAlignment = Enum.TextYAlignment.Top;
				l:UpdateContent(w, f, d);
				function q.SetTitle(k, l)
					f.Text = l;
				end;
				function q.SetDesc(k, l)
					w.Text = l;
				end;
				return q;
			end;
			return E;
		end;
		return K;
	end;
	local U = {};
	U["1"] = Instance.new("ScreenGui", (game:GetService("Players")).LocalPlayer:WaitForChild("PlayerGui"));
	U["1"].ZIndexBehavior = Enum.ZIndexBehavior.Sibling;
	U["2"] = Instance.new("ImageButton", U["1"]);
	U["2"].BorderSizePixel = 0;
	U["2"].Visible = true;
	I:MakeDraggable(U["2"], U["2"]);
	U["2"].BackgroundColor3 = Color3.fromRGB(255, 255, 255);
	U["2"].Image = "rbxassetid://83491390959705";
	U["2"].Size = UDim2.new(0, 50, 0, 50);
	U["2"].BorderColor3 = Color3.fromRGB(0, 0, 0);
	U["2"].Position = UDim2.new(.26651, 0, .43687, 0);
	U["3"] = Instance.new("UICorner", U["2"]);
	U["3"].CornerRadius = UDim.new(1, 0);
	U["4"] = Instance.new("UIStroke", U["2"]);
	U["4"].Thickness = 2;
	U["4"].Color = Color3.fromRGB(255, 92, 220);
	U["2"].MouseButton1Click:Connect(function()
		d.Enabled = not d.Enabled;
	end);
	C.MouseButton1Click:Connect(function()
		d.Enabled = false;
	end);
	return L;
end;
return l;